name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: '3.11'
    steps:
    - uses: actions/checkout@v3
    - name: Set up Conda environment with Python ${{ matrix.python-version }}
      uses: s-weigand/setup-conda@v1
      with:
        python-version: ${{ matrix.python-version }}
        conda-channels: 'conda-forge'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install pandas
        pip install requests
        pip install validators
        pip install opencv-python
        conda env update --file environment.yml
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
